"""qemu:commandline args for a Profile (plan 02 "genxml closure").

Emits the libvirt qemu-namespace <arg> list that libvirt appends to the
qemu command line. These are the knobs libvirt has no native element
for. This is the exact set the live aptwannabe domain carries:

  -machine  full machine.args passthrough (pc-q35-11.0,usb=off,...)
  -smbios   file=<smbios.file> (DMI blob generated by SMBIOS.py)
  -acpitable file=<firmware>/<name>.aml for each acpitable.files entry

AML blobs live under patches/QEMU/ in the repo and are staged to
/opt/vmw/firmware/ by the deploy step's copy_aml action; the args
reference the staged location, not the repo path.
"""

from __future__ import annotations

from pathlib import Path

from vmw.profiles.schema import Profile

# Where the deploy step stages .aml blobs (OUT_DIR/firmware).
FIRMWARE_DIR = Path("/opt/vmw/firmware")


def qemu_commandline_args(profile: Profile, firmware_dir: Path = FIRMWARE_DIR) -> list[str]:
    """Flat argv list: ['-machine', '...', '-smbios', 'file=...', ...]."""
    args: list[str] = ["-machine", profile.machine.args]

    if profile.smbios.file:
        args += ["-smbios", f"file={profile.smbios.file}"]

    for name in profile.acpitable.files:
        path = firmware_dir / name
        args += ["-acpitable", f"file={path}"]

    return args
